backend:
  name: git-gateway
  branch: main # Branch to update (master or main)

media_folder: "images/uploads" # Media files will be stored here
public_folder: "/images/uploads" # The src attribute for uploaded media

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog Posts" # Used in the UI
    folder: "data/posts" # The path to the folder where files are stored
    create: true # Allow users to create new documents
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template
    fields: # The fields for each document
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", default: ["AI", "Marketing"]}
      - {label: "SEO Title", name: "seo_title", widget: "string"}
      - {label: "SEO Description", name: "seo_description", widget: "text"}
